Update menu_inst

diff --git a/menu_inst b/menu_inst
--- a/menu_inst
+++ b/menu_inst
@@ -376,45 +376,84 @@ for ufww in $(mportas|awk '{print $2}'); do
 ufw allow $ufww > /dev/null 2>&1
 done
 }
-
-
+dns_fun () {
+case $1 in
+3)dns[$2]='push "dhcp-option DNS 1.0.0.1"';;
+4)dns[$2]='push "dhcp-option DNS 1.1.1.1"';;
+5)dns[$2]='push "dhcp-option DNS 9.9.9.9"';;
+6)dns[$2]='push "dhcp-option DNS 1.1.1.1"';;
+7)dns[$2]='push "dhcp-option DNS 80.67.169.40"';;
+8)dns[$2]='push "dhcp-option DNS 80.67.169.12"';;
+9)dns[$2]='push "dhcp-option DNS 84.200.69.80"';;
+10)dns[$2]='push "dhcp-option DNS 84.200.70.40"';;
+11)dns[$2]='push "dhcp-option DNS 208.67.222.222"';;
+12)dns[$2]='push "dhcp-option DNS 208.67.220.220"';;
+13)dns[$2]='push "dhcp-option DNS 8.8.8.8"';;
+14)dns[$2]='push "dhcp-option DNS 8.8.4.4"';;
+15)dns[$2]='push "dhcp-option DNS 77.88.8.8"';;
+16)dns[$2]='push "dhcp-option DNS 77.88.8.1"';;
+17)dns[$2]='push "dhcp-option DNS 176.103.130.130"';;
+18)dns[$2]='push "dhcp-option DNS 176.103.130.131"';;
+esac
+}
+meu_ip () {
+if [[ -e /etc/MEUIPADM ]]; then
+echo "$(cat /etc/MEUIPADM)"
+else
+MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
+[[ "$MEU_IP" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
+echo "$MEU_IP2" > /etc/MEUIPADM
+fi
+}
+IP="$(meu_ip)"
+fun_bar () {
+comando="$1"
+ _=$(
+$comando > /dev/null 2>&1
+) & > /dev/null
+pid=$!
+while [[ -d /proc/$pid ]]; do
+echo -ne " \033[1;33m["
+   for((i=0; i<10; i++)); do
+   echo -ne "\033[1;31m##"
+   sleep 0.2
+   done
+echo -ne "\033[1;33m]"
+sleep 1s
+echo
+tput cuu1
+tput dl1
+done
+echo -e " \033[1;33m[\033[1;31m####################\033[1;33m] - \033[1;32m100%\033[0m"
+sleep 1s
+}
 instala_ovpn () {
 parametros_iniciais () {
 #Verifica o Sistema
-if [[ "$EUID" -ne 0 ]]; then
-	echo -e "$barra"
-	echo " Sorry, you need to run this as root"
-	echo -e "$barra"
-	read -p " Enter"
-	exit
-fi
-
-if [[ ! -e /dev/net/tun ]]; then
-	echo -e "$barra"
-	echo " The TUN device is not available"
-	echo -e "$barra"
-	read -p " Enter" 
-	exit
-fi
+[[ "$EUID" -ne 0 ]] && echo "Desculpe, você precisa rodar isso como root" && return 1
+[[ ! -e /dev/net/tun ]] && echo "TUN não está disponível" && return 1
 if [[ -e /etc/debian_version ]]; then
 OS="debian"
 VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
 IPTABLES='/etc/iptables/iptables.rules'
+[[ ! -d /etc/iptables ]] && mkdir /etc/iptables
+[[ ! -e $IPTABLES ]] && touch $IPTABLES
 SYSCTL='/etc/sysctl.conf'
  [[ "$VERSION_ID" != 'VERSION_ID="7"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="8"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="9"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="14.04"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="16.04"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="17.10"' ]] && {
  echo " Sua versão do Debian / Ubuntu não é suportada."
  while [[ $CONTINUE != @(y|Y|s|S|n|N) ]]; do
  read -p "Continuar ? [y/n]: " -e CONTINUE
  done
- [[ "$CONTINUE" = @(n|N) ]] && return 2
+ [[ "$CONTINUE" = @(n|N) ]] && exit 1
  }
 else
-echo -e "$barra\n\033[1;33m $(source trans -b pt:${id} "Parece que você não está executando este instalador em um sistema Debian ou Ubuntu")\n$barra"
+echo -e "\033[1;33m $(fun_trans ${id} "Parece que voce nao esta executando este instalador em um sistema Debian ou Ubuntu")\n$barra"
 return 1
 fi
 #Pega Interface
 NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1)
-echo -e "$barra\n\033[1;33m $(source trans -b pt:${id} "Sistema Preparado Para Receber o OPENVPN")\n$barra"
+echo -e "\033[1;33m $(fun_trans ${id} "Sistema Preparado Para Receber o OPENVPN")\n$barra"
 }
 add_repo () {
 #INSTALACAO E UPDATE DO REPOSITORIO
@@ -433,86 +472,89 @@ wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add - > /
 fi
 }
 coleta_variaveis () {
-	#Instal
-	echo -e " $(source trans -b pt:${id} "Responda as perguntas para iniciar a instalacao")"
-	echo -e " $(source trans -b pt:${id} "Responda corretamente")\n$barra "
-	echo -e " \033[1;33m$(source trans -b pt:${id} "Primeiro precisamos do ip de sua maquina, este ip esta correto?")\033[0m"
-	# Autodetect IP address and pre-fill for the user
-	IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
-	read -p " IP address: " -e -i $IP IP
-	# If $IP is a private IP address, the server must be behind NAT
-	if echo "$IP" | grep -qE '^(10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.|192\.168)'; then
-		echo
-		echo " \033[1;33m$(source trans -b en:${id} This server is behind NAT. What is the public IPv4 address or hostname?)"
-		read -p " Public IP address / hostname: " -e PUBLICIP
-	fi
-	echo -e "$barra\n \033[1;31m$(source trans -b es:${id} "Elegir el tipo de protocolo para") OPENVPN"
-	echo -e " \033[1;31m$(source trans -b pt:${id} "A menos que o UDP esteja bloqueado, você não deve usar o TCP (mais lento)")\n$barra"
-	#PROTOCOLO
-	while [[ $PROTOCOL != @(UDP|TCP) ]]; do
-	read -p " Protocol [UDP/TCP]: " -e -i TCP PROTOCOL
-	done
-	[[ $PROTOCOL = "UDP" ]] && PROTOCOL=udp
-	[[ $PROTOCOL = "TCP" ]] && PROTOCOL=tcp
-	echo -e "$barra\n \033[1;33m$(source trans -b pt:${id} "Qual porta voce deseja usar?")\033[0m\n$barra"
-	read -p " Port: " -e -i 1194 PORT
-	#DNS
-	echo -e "$barra\n \033[1;33m$(source trans -b pt:${id} "Qual DNS voce deseja usar?")\n$barra"
-	echo "   1) Usar DNS del sistema"
-	echo "   2) Cloudflare (Anycast: worldwide)"
-	echo "   3) Quad9 (Anycast: worldwide)"
-	echo "   4) FDN (France)"
-	echo "   5) DNS.WATCH (Germany)"
-	echo "   6) OpenDNS (Anycast: worldwide)"
-	echo "   7) Google (Anycast: worldwide)"
-	echo "   8) Yandex Basic (Russia)"
-	echo "   9) AdGuard DNS (Russia)"
-	while [[ $DNS != @(1|2|3|4|5|6|7|8|9) ]]; do
-	read -p " DNS [1-9]: " -e -i 1 DNS
-	done
-	#CIPHER
-	echo -e "$barra\n \033[1;33m$(source trans -b es:${id} "Elegir el tipo de codificacion para el canal de datos:")\n$barra"
-	echo "   1) AES-128-CBC"
-	echo "   2) AES-192-CBC"
-	echo "   3) AES-256-CBC"
-	echo "   4) CAMELLIA-128-CBC"
-	echo "   5) CAMELLIA-192-CBC"
-	echo "   6) CAMELLIA-256-CBC"
-	echo "   7) SEED-CBC"
-	while [[ $CIPHER != @(1|2|3|4|5|6|7) ]]; do
-	read -p " Cipher [1-7]: " -e -i 1 CIPHER
-	done
-	case $CIPHER in
-	1) CIPHER="cipher AES-128-CBC";;
-	2) CIPHER="cipher AES-192-CBC";;
-	3) CIPHER="cipher AES-256-CBC";;
-	4) CIPHER="cipher CAMELLIA-128-CBC";;
-	5) CIPHER="cipher CAMELLIA-192-CBC";;
-	6) CIPHER="cipher CAMELLIA-256-CBC";;
-	7) CIPHER="cipher SEED-CBC";;
-	esac
-	echo -e "$barra\n \033[1;33m$(source trans -b pt:${id} "Estamos prontos para configurar seu servidor OpenVPN")\n$barra"
-	read -n1 -r -p " Enter to Continue..."
-	echo -e "$barra"
-	}
+echo -e " $(fun_trans ${id} "Responda as perguntas para iniciar a instalacao")"
+echo -e " $(fun_trans ${id} "Responda corretamente")"
+echo -e "\033[1;33m$(fun_trans ${id} "Primeiro precisamos do ip de sua maquina, este ip esta correto?")\033[0m"
+read -p "IP address: " -e -i $IP IP
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Qual porta voce deseja usar?")\033[0m\n$barra"
+read -p "Port: " -e -i 1194 PORT
+echo -e "\033[1;31m$(fun_trans ${id} "Qual protocolo voce deseja para as conexoes OPENVPN?")"
+echo -e "\033[1;31m$(fun_trans ${id} "A menos que o UDP esteja bloqueado, voce nao deve usar o TCP (mais lento)")"
+#PROTOCOLO
+while [[ $PROTOCOL != @(UDP|TCP) ]]; do
+read -p "Protocol [UDP/TCP]: " -e -i TCP PROTOCOL
+done
+[[ $PROTOCOL = "UDP" ]] && PROTOCOL=udp
+[[ $PROTOCOL = "TCP" ]] && PROTOCOL=tcp
+#DNS
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Qual DNS voce deseja usar?")\n$barra"
+echo "   1) Usar padrões do sistema "
+echo "   2) Cloudflare"
+echo "   3) Quad"
+echo "   4) FDN"
+echo "   5) DNS.WATCH"
+echo "   6) OpenDNS"
+echo "   7) Google DNS"
+echo "   8) Yandex Basic"
+echo "   9) AdGuard DNS"
+while [[ $DNS != @([1-9]) ]]; do
+read -p "DNS [1-9]: " -e -i 1 DNS
+done
+#CIPHER
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Escolha qual codificação você deseja usar para o canal de dados:")\n$barra"
+echo "   1) AES-128-CBC"
+echo "   2) AES-192-CBC"
+echo "   3) AES-256-CBC"
+echo "   4) CAMELLIA-128-CBC"
+echo "   5) CAMELLIA-192-CBC"
+echo "   6) CAMELLIA-256-CBC"
+echo "   7) SEED-CBC"
+while [[ $CIPHER != @([1-7]) ]]; do
+read -p "Cipher [1-7]: " -e -i 1 CIPHER
+done
+case $CIPHER in
+1) CIPHER="cipher AES-128-CBC";;
+2) CIPHER="cipher AES-192-CBC";;
+3) CIPHER="cipher AES-256-CBC";;
+4) CIPHER="cipher CAMELLIA-128-CBC";;
+5) CIPHER="cipher CAMELLIA-192-CBC";;
+6) CIPHER="cipher CAMELLIA-256-CBC";;
+7) CIPHER="cipher SEED-CBC";;
+esac
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Estamos prontos para configurar seu servidor OpenVPN")\n$barra"
+read -n1 -r -p "Enter to Continue..."
+}
 parametros_iniciais # BREVE VERIFICACAO
 coleta_variaveis # COLETA VARIAVEIS PARA INSTALAÇÃO
 add_repo # ATUALIZA REPOSITÓRIO OPENVPN E INSTALA OPENVPN
 # Cria Diretorio
 [[ ! -d /etc/openvpn ]] && mkdir /etc/openvpn
 # Install openvpn
-echo -ne "\033[1;31m [ ! ] apt-get update"
-apt-get update -q > /dev/null 2>&1 && echo -e "\033[1;32m [OK]"
-echo -ne "\033[1;31m [ ! ] apt-get install openvpn curl openssl"
-apt-get install -qy openvpn curl > /dev/null 2>&1 && apt-get install openssl -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]"
-# IP Address
-SERVER_IP=$(wget -qO- ipv4.icanhazip.com)
-if [[ -z "${SERVER_IP}" ]]; then
-    SERVER_IP=$(ip a | awk -F"[ /]+" '/global/ && !/127.0/ {print $3; exit}')
-fi
-# Generate CA Config
-echo -ne "\033[1;31m [ ! ] Generating CA Config"
+echo -ne "\033[1;31m[ ! ] apt-get update"
+apt-get update -q > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne "\033[1;31m[ ! ] apt-get install openvpn curl openssl"
+apt-get install -qy openvpn curl > /dev/null 2>&1 && apt-get install openssl -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+SERVER_IP="$(meu_ip)" # IP Address
+[[ -z "${SERVER_IP}" ]] && SERVER_IP=$(ip a | awk -F"[ /]+" '/global/ && !/127.0/ {print $3; exit}')
+echo -ne "\033[1;31m[ ! ] Generating Server Config" # Gerando server.con
 (
+case $DNS in
+1)
+i=0
+grep -v '#' /etc/resolv.conf | grep 'nameserver' | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | while read line; do
+dns[$i]="push \"dhcp-option DNS $line\""
+done
+[[ ! "${dns[@]}" ]] && dns[0]='push "dhcp-option DNS 8.8.8.8"' && dns[1]='push "dhcp-option DNS 8.8.4.4"'
+;;
+2)dns_fun 3 && dns_fun 4;;
+3)dns_fun 5 && dns_fun 6;;
+4)dns_fun 7 && dns_fun 8;;
+5)dns_fun 9 && dns_fun 10;;
+6)dns_fun 11 && dns_fun 12;;
+7)dns_fun 13 && dns_fun 14;;
+8)dns_fun 15 && dns_fun 16;;
+9)dns_fun 17 && dns_fun 18;;
+esac
 echo 01 > /etc/openvpn/ca.srl
 while [[ ! -e /etc/openvpn/dh.pem || -z $(cat /etc/openvpn/dh.pem) ]]; do
 openssl dhparam -out /etc/openvpn/dh.pem 2048 &>/dev/null
@@ -527,54 +569,6 @@ done
 while [[ ! -e /etc/openvpn/ca.pem || -z $(cat /etc/openvpn/ca.pem) ]]; do
 openssl x509 -req -in /etc/openvpn/ca-csr.pem -out /etc/openvpn/ca.pem -signkey /etc/openvpn/ca-key.pem -days 365 &>/dev/null
 done
-) && echo -e "\033[1;32m [OK]"
-# Gerando server.con
-echo -ne "\033[1;31m [ ! ] Generating Server Config"
-(
-case $DNS in
-1)
-i=0
-grep -v '#' /etc/resolv.conf | grep 'nameserver' | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | while read line; do
-dns[$i]="push \"dhcp-option DNS $line\""
-done
-if [[ ! "${dns[@]}" ]]; then
-dns[0]='push "dhcp-option DNS 8.8.8.8"'
-dns[1]='push "dhcp-option DNS 8.8.4.4"'
-fi
-;;
-2)
-dns[0]='push "dhcp-option DNS 1.0.0.1"'
-dns[1]='push "dhcp-option DNS 1.1.1.1"'
-;;
-3)
-dns[0]='push "dhcp-option DNS 9.9.9.9"'
-dns[1]='push "dhcp-option DNS 1.1.1.1"'
-;;
-4)
-dns[0]='push "dhcp-option DNS 80.67.169.40"'
-dns[1]='push "dhcp-option DNS 80.67.169.12"'
-;;
-5)
-dns[0]='push "dhcp-option DNS 84.200.69.80"'
-dns[1]='push "dhcp-option DNS 84.200.70.40"'
-;;
-6)
-dns[0]='push "dhcp-option DNS 208.67.222.222"'
-dns[1]='push "dhcp-option DNS 208.67.220.220"'
-;;
-7)
-dns[0]='push "dhcp-option DNS 8.8.8.8"'
-dns[1]='push "dhcp-option DNS 8.8.4.4"'
-;;
-8)
-dns[0]='push "dhcp-option DNS 77.88.8.8"'
-dns[1]='push "dhcp-option DNS 77.88.8.1"'
-;;
-9)
-dns[0]='push "dhcp-option DNS 176.103.130.130"'
-dns[1]='push "dhcp-option DNS 176.103.130.131"'
-;;
-esac
 cat > /etc/openvpn/server.conf <<EOF
 server 10.8.0.0 255.255.255.0
 verb 3
@@ -609,10 +603,8 @@ client-cert-not-required
 username-as-common-name
 plugin $PLUGIN login" >> /etc/openvpn/server.conf
 }
-) && echo -e "\033[1;32m [OK]"
-
-# Generate Client Config
-echo -ne "\033[1;31m [ ! ] Generating Client Config"
+) && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne "\033[1;31m[ ! ] Generating CA Config" # Generate CA Config
 (
 while [[ ! -e /etc/openvpn/client-key.pem || -z $(cat /etc/openvpn/client-key.pem) ]]; do
 openssl genrsa -out /etc/openvpn/client-key.pem 2048 &>/dev/null
@@ -624,28 +616,25 @@ done
 while [[ ! -e /etc/openvpn/client-cert.pem || -z $(cat /etc/openvpn/client-cert.pem) ]]; do
 openssl x509 -req -in /etc/openvpn/client-csr.pem -out /etc/openvpn/client-cert.pem -CA /etc/openvpn/ca.pem -CAkey /etc/openvpn/ca-key.pem -days 365 &>/dev/null
 done
-) && echo -e "\033[1;32m [OK]"
+) && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
 teste_porta () {
-  echo -ne " \033[1;31m$(source trans -b es:${id} "Verificando: ")"
+  echo -ne "\033[1;31m$(fun_trans ${id} "Verificando")"
   sleep 1s
-  [[ ! $(mportas | grep $1) ]] && {
-    echo -e " \033[1;33m$(source trans -b es:${id} "Abriendo un Puerto en Python")"
-    cd /etc/adm-lite
-    [[ $(screen -h|wc -l) -lt '30' ]] && apt-get install screen -y 
-    screen -dmS screen python ./openproxy.py "$1"    
+  [[ ! $(mportas | grep "$1") ]] && {
+    echo -e "$(fun_trans ${id} "\033[1;33m [Porta Invalida!]")"
     } || {
     echo -e "\033[1;32m [Pass]"
     return 1
     }
    }
-echo -e "$barra\n \033[1;33m$(source trans -b es:${id} "Ahora se necesita el puerto de su Proxy Squid (Socks)")"
-echo -e " \033[1;33m$(source trans -b pt:${id} "Se nao Existir Proxy na Porta um Proxy Python sera Aberto!")\n$barra"
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Agora Precisamos da Porta Que Esta Seu Proxy Squid(Socks)")"
+echo -e "\033[1;33m$(fun_trans ${id} "Se nao Existir Proxy na Porta um Proxy Python sera Aberto!")\n$barra"
 while [[ $? != "1" ]]; do
-read -p " Confirme un Puerto(Proxy): " -e -i 80 PPROXY
+read -p "Confirme a Porta(Proxy): " -e -i 80 PPROXY
 teste_porta $PPROXY
 done
 cat > /etc/openvpn/client-common.txt <<EOF
-# OVPN_ACCESS_SERVER_PROFILE=Adm-Ultimate
+# OVPN_ACCESS_SERVER_PROFILE=New-Ultimate
 client
 nobind
 dev tun
@@ -732,6 +721,7 @@ sed -i "/127.0.0.1[[:blank:]]\+localhost/a 127.0.0.1 $NEWDNS" /etc/hosts
 for DENESI in $(echo $NEWDNS); do
 sed -i "/remote ${SERVER_IP} ${PORT} ${PROTOCOL}/a remote ${DENESI} ${PORT} ${PROTOCOL}" /etc/openvpn/client-common.txt
 done
+}
 echo -e "$barra"
 # REINICIANDO OPENVPN
 if [[ "$OS" = 'debian' ]]; then
@@ -740,46 +730,30 @@ if [[ "$OS" = 'debian' ]]; then
  sed -i 's|/etc/openvpn/server|/etc/openvpn|' /lib/systemd/system/openvpn\@.service
  sed -i 's|%i.conf|server.conf|' /lib/systemd/system/openvpn\@.service
  #systemctl daemon-reload
- (
  systemctl restart openvpn
  systemctl enable openvpn
- ) > /dev/null 2>&1
- echo -ne
  else
  /etc/init.d/openvpn restart
  fi
 else
  if pgrep systemd-journal; then
-  (
  systemctl restart openvpn@server.service
  systemctl enable openvpn@server.service
-  ) > /dev/null 2>&1
-  echo -ne
  else
  service openvpn restart
  chkconfig openvpn on
  fi
 fi
+service squid restart &>/dev/null
+service squid3 restart &>/dev/null
 apt-get install ufw -y > /dev/null 2>&1
 for ufww in $(mportas|awk '{print $2}'); do
 ufw allow $ufww > /dev/null 2>&1
 done
-#Restart OPENVPN
-(
-killall openvpn 2>/dev/null
-systemctl stop openvpn@server.service > /dev/null 2>&1
-service openvpn stop > /dev/null 2>&1
-sleep 0.1s
-cd /etc/openvpn > /dev/null 2>&1
-/etc/iptables-openvpn > /dev/null 2>&1
-openvpn --config server.conf & > /dev/null 2>&1
-) > /dev/null 2>&1
-echo -e "$barra\n \033[1;33m$(source trans -b pt:${id} "Openvpn Configurado Com Sucesso!")"
-echo -e " \033[1;33m$(source trans -b pt:${id} "Agora Criar Um Usuario Para Gerar um Cliente!")\n$barra"
+echo -e "$barra\n\033[1;33m$(fun_trans ${id} "Openvpn Configurado Com Sucesso!")"
+echo -e "\033[1;33m$(fun_trans ${id} "Agora So Criar Um Usuario Para Gerar um Cliente!")\n$barra"
 return 0
-}
-
-	
+}	
 fun_openvpn () {
 [[ -e /etc/openvpn/server.conf ]] && {
 unset OPENBAR
